version: "3"

services:
  api_solid_pg:
    image: bitnami/postgresql
    container_name: api_solid_pg
    ports:
      - "5433:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
